name: grade-notifier
on:
  schedule:
    - cron: '0,30 5-16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-dotenv schedule
      - name: Debug secrets
        env:
          ZAMBEEL_USER: ${{ secrets.ZAMBEEL_USER }}
          ZAMBEEL_PASS: ${{ secrets.ZAMBEEL_PASS }}
        run: |
          echo "User length: ${#ZAMBEEL_USER}"
          echo "Pass length: ${#ZAMBEEL_PASS}"
          echo "User first char: ${ZAMBEEL_USER:0:1}"
          echo "User last char: ${ZAMBEEL_USER: -1}"


      - name: Run Script
        env:
          ZAMBEEL_USER: ${{ secrets.ZAMBEEL_USER }}
          ZAMBEEL_PASS: ${{ secrets.ZAMBEEL_PASS }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          UNI_EMAIL: ${{ secrets.UNI_EMAIL }}
          EMP_ID: ${{ secrets.EMP_ID }}
        run: python script.py
      
      - name: Commit new data
        run: |
          git config --global user.name "Grade Watcher Bot"
          git config --global user.email "actions@github.com"
          git add last_grades.json
          git diff --staged --quiet || (git commit -m "Update last_grades.json" && git push)